Overrides to rebalance techshells, mostly nerfs.
MrMelbert/MapleStationCode pull request #156
Opened 2022-05-09 05:34 UTC by CRITAWAKETS

So, tech shells have been nerfed. Here's the changelog.

Frag-12 no longer has the innate damage and stunning, the explosion already causes a LOT of damage.
Laser Scatter now does 66 damage over it's 6 pellets (11 per pellet) instead of 90 over it's 6 pellets (15 per pellet). This ends up being under 50 when wearing an armor vest!
Meteor slugs are now a true war crime of a projectile, no longer stunning their opponents and knocking them down for shorter times, but causing an incredible amount of pain.

2022-05-11 23:29 UTC, MrMelbert requested changes

2022-05-11 23:29 UTC, MrMelbert commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +			M.cause_pain(BODY_ZONES_ALL, 50) //OW MY BONES
Better variable name than `M`

2022-05-11 23:41 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +			M.cause_pain(BODY_ZONES_ALL, 50) //OW MY BONES
Yeah sharp pain seems better, would certainly work better for security uses.

2022-05-12 01:53 UTC, MrMelbert requested changes

2022-05-12 01:53 UTC, MrMelbert commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +	knockdown = 50
```suggestion
	knockdown = 5 SECONDS
```

2022-05-12 01:53 UTC, MrMelbert commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +			unfortunate_soul.sharp_pain(BODY_ZONES_ALL, 50) //OW MY BONES
iirc `sharp_pain` already checks for the existence of pain controller, so you can just apply it without concern (needing to sanity check)

2022-05-12 01:59 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +			unfortunate_soul.sharp_pain(BODY_ZONES_ALL, 50) //OW MY BONES
It doesn't, actually.

2022-05-14 06:30 UTC, MrMelbert commented on maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
> +			unfortunate_soul.sharp_pain(BODY_ZONES_ALL, 50) //OW MY BONES
![image](https://user-images.githubusercontent.com/51863163/168413856-29e63b44-66a5-41a7-b3d4-6305a05c1d34.png)

2022-05-14 06:36 UTC, merged