Ports the Eggcellent Challenge from HS
MrMelbert/MapleStationCode pull request #263
Opened 2023-04-12 04:46 UTC by Wallemations

Beat the challenge, get the hat, save your dying friend!

Now with new **`NAMELESS HERO`** difficulty! _(Nameless hero difficulty does not gain you any additional benefits upon completing challenge.)_

2023-04-12 18:24 UTC, Wallemations commented
what the hell happened that made this fail

2023-04-14 00:02 UTC, CRITAWAKETS requested changes
code is pretty good, though you'll wanna switch out the single-letter variable names

2023-04-14 00:02 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/food_and_drinks/recipes/food/egg_recipes.dm
> +// Egcellent Challenge
```suggestion
// Eggcellent Challenge
```

2023-04-14 00:02 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/food_and_drinks/food/eggs.dm
> +/obj/item/food/omelette/eggcellent_plate/proc/On_Consume(atom/eggs, mob/egg_eater, mob/egg_feeder)
WHY IS THIS WITH UPPERCASE WHAT ARE YOU DOIINNGGGGGG

2023-04-14 00:31 UTC, CRITAWAKETS requested changes

2023-04-14 00:31 UTC, CRITAWAKETS commented on maplestation.dme
>  #include "maplestation_modules\code\modules\food_and_drinks\recipes\drinks_recipes.dm"
```suggestion
#include "maplestation_modules\code\modules\food_and_drinks\recipes\drinks_recipes.dm"
#include "maplestation_modules\code\modules\food_and_drinks\recipes\food\egg_recipes.dm"
```

ah shit these need to be reversed too

2023-04-16 21:39 UTC, Wallemations commented on maplestation_modules/code/modules/food_and_drinks/food/eggs.dm
> +	priority_announce("[current_challenger] has failed to finish [current_challenger.p_their()] quest in the given timeframe. Measures have been taken accordingly.", "Sacred Egg Enrichment Center")
I think I've got an idea for that

2023-04-18 13:35 UTC, Wallemations commented on maplestation_modules/code/modules/food_and_drinks/food/eggs.dm
> +	loc.visible_message(flavor_text)
I didn't even think of that, I'll have to swap it out

2023-04-22 18:24 UTC, merged