[DRAFT] adds a new species, ornithids idk i'm losing my sanity
MrMelbert/MapleStationCode pull request #270
Opened 2023-05-03 02:35 UTC by Wollywoger

yes, there are 41+ commits. this was branched off of the time organs, which i had accidentally worked in the plasma blade branch  aaaaaaaaaaaaaaaaaaaaa
## TODO

- [ ] Get arm wings pref added
- [ ] have flight working
- [ ] sub task of above: have the hand restriction when flying
- [ ] make the arm wing sprites
- [ ] add any other organs/details i might want

## NON MODULAR CHANGES
this adds a new DNA slot, and copies a lot of code from skrell's head tentacles. any case of this is marked down with a comment, even when there is a similar one above.

2023-06-10 04:18 UTC, Wollywoger commented
wew lad, finally got the wing sprites to appear on mob, after procrastinating on it

2023-06-24 20:57 UTC, Wollywoger commented
the monkey business unit test is a failure magnet, hence why pubbystation (and only pubbystation) integration tests fail.

2023-06-27 04:25 UTC, MrMelbert requested changes

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +	// THIS SHOULD ONLY APPLY WHEN THE USER IS FLYING (or floating, because that makes sense, i guess)!!!!
You can use `movetypes = FLOATING|FLYING` to make it only apply to those movetypes

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +/datum/sprite_accessory/arm_wings
```suggestion
	return ..()
	
/datum/sprite_accessory/arm_wings
```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +
```suggestion

```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +
```suggestion

```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +// ear code here
Do you perhaps want to make 1 folder and put each feature in a separate file?

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +	return ..() // todo: add code for checking if arms are disabled through paralysis or damage
You can check `human.usable_arms > 0` (arms are not usable when paralyzed or disabed)

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +		BODY_ZONE_CHEST = /obj/item/bodypart/chest/,
```suggestion
		BODY_ZONE_HEAD = /obj/item/bodypart/head, // just because they are still *partially* human, or otherwise human resembling
		BODY_ZONE_L_LEG = /obj/item/bodypart/leg/left,
		BODY_ZONE_R_LEG = /obj/item/bodypart/leg/right,
		BODY_ZONE_CHEST = /obj/item/bodypart/chest,
```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	//	/obj/item/organ/external/tail/avian = "[-TODO-]",
```suggestion
	//	/obj/item/organ/external/tail/avian = "[-TODO-]",
```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	)
I find it quite funny these chaps can't use wing potions. Not suggesting it needs to be changed (needs sprites after all) just musing

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	disliked_food = DAIRY | CLOTH | GROSS | SUGAR // Chocolate is toxic to birds (but not to these guys, they just find it nasty). Also, this forces a dietary difference ala lizards.
`toxic_food = SUGAR` would fill an interesting niche (being unable to have sweets) - Not suggesting it has to change, just mentioning it

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +		),
```suggestion
		list(
			SPECIES_PERK_TYPE = SPECIES_POSITIVE_PERK,
			SPECIES_PERK_ICON = "dove",
			SPECIES_PERK_NAME = "Airborne",
			SPECIES_PERK_DESC = "Is it a bird? is it a plane? Of course its a bird you dumbass, \
				Ornithids are lightweight winged avians, and can, as a result, fly.",
		),
```
Repeat for the rest of the perks

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/surgery/organs/tongue.dm
> +
```suggestion
/obj/item/organ/internal/tongue/ornithid
	name = "avian tongue"
	desc = "A seemingly normal looking tongue which causes ones voice to caw. However that works."
	say_mod = "caws"

```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +GLOBAL_LIST_EMPTY(tails_list_avian)
Comment this tails list out?

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> +/datum/species/lizard/prepare_human_for_preview(mob/living/carbon/human/human) // this is used to generate the previews in the species menu of the prefs tab.
Don't need to re-add this comment

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/client/preferences/species/ornithid.dm
> +
```suggestion

/datum/preference/choiced/plumage/init_possible_values()
	return possible_values_for_sprite_accessory_list_for_body_part(
		GLOB.avian_ears_list,
		"ears_avian",
		list("FRONT"),
	)

```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/client/preferences/species/ornithid.dm
> +		)
```suggestion
	)
```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/client/preferences/species/ornithid.dm
> +		if (sprite_accessory.icon_state != "none")
If you don't have a "none" icon state (and I hope you don't) i'd axe this

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +/datum/species/ornithid
I *think* you must implement `randomize_features` for your species? Maybe?

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	use_skintones = 1
```suggestion
	use_skintones = TRUE
```

2023-06-27 04:25 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	inherent_biotypes = MOB_ORGANIC|MOB_HUMANOID
```suggestion
```
Default setting

2023-06-27 06:00 UTC, Wollywoger commented on maplestation_modules/code/modules/client/preferences/species/ornithid.dm
> +		if (sprite_accessory.icon_state != "none")
yeah this was copied from skrell code, i'll delete this instance

2023-06-27 06:04 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +	// THIS SHOULD ONLY APPLY WHEN THE USER IS FLYING (or floating, because that makes sense, i guess)!!!!
added

2023-06-27 06:10 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +	return ..() // todo: add code for checking if arms are disabled through paralysis or damage
human.usable_arms is not defined, closest is human.usable_hands, which more than likely won't work

2023-06-27 06:11 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> +/datum/species/lizard/prepare_human_for_preview(mob/living/carbon/human/human) // this is used to generate the previews in the species menu of the prefs tab.
how did that even end up here

2023-06-27 06:13 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +		BODY_ZONE_CHEST = /obj/item/bodypart/chest/,
hold over from when the whole thing was unique parts, when i didn't understand part/limb code

2023-06-27 06:14 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	disliked_food = DAIRY | CLOTH | GROSS | SUGAR // Chocolate is toxic to birds (but not to these guys, they just find it nasty). Also, this forces a dietary difference ala lizards.
that would actually work, applying in the next commit

2023-06-27 06:14 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +	disliked_food = DAIRY | CLOTH | GROSS | SUGAR // Chocolate is toxic to birds (but not to these guys, they just find it nasty). Also, this forces a dietary difference ala lizards.
addendum: previously thought against that because of the Felinid Chocolate Incident

2023-06-27 06:16 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +		),
done, adding in a VScode batch.

2023-06-27 06:35 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features.dm
> +// ear code here
done

2023-06-27 18:51 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +/datum/species/ornithid
done, atleast i think

2023-06-28 22:49 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/species_types/ornithid.dm
> +/datum/species/ornithid
done

2023-07-02 00:46 UTC, MrMelbert requested changes
Nitpicks

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +	// THIS SHOULD ONLY APPLY WHEN THE USER IS FLYING (or floating, because that makes sense, i guess)!!!!
```suggestion
```

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +/datum/movespeed_modifier/arm_wing_flight // putting it here because this is the relevant file, and insular use case.
```suggestion
/datum/movespeed_modifier/arm_wing_flight 
```

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +	if(HAS_TRAIT(human, TRAIT_RESTRAINED)) // prevents from flying if cuffed/restrained.
```suggestion
	if(HAS_TRAIT(human, TRAIT_RESTRAINED))
```

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +	return ..() // todo: add code for checking if arms are disabled through paralysis or damage
Did you not come round to checking this with usable hands or whatever?

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +		ADD_TRAIT(human, TRAIT_HANDS_BLOCKED, REF(src)) //  If someone knows how to get the crossed out markers to appear in hand, please let me know
```suggestion
		ADD_TRAIT(human, TRAIT_HANDS_BLOCKED, REF(src)) //  If someone knows how to get the crossed out markers to appear in hand, please let me know
```
You'd need to mark the arms as `disabled` to accomplish this.

2023-07-02 00:46 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +/datum/bodypart_overlay/mutant/wings/arm_wings/get_global_feature_list()
```suggestion
	color_src = HAIR
	
/datum/bodypart_overlay/mutant/wings/arm_wings
	feature_key = "arm_wings"
	layers = EXTERNAL_FRONT
	color_source = ORGAN_COLOR_HAIR
	
/datum/bodypart_overlay/mutant/wings/arm_wings/get_global_feature_list()
```

2023-07-02 01:01 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +		ADD_TRAIT(human, TRAIT_HANDS_BLOCKED, REF(src)) //  If someone knows how to get the crossed out markers to appear in hand, please let me know
got it, i'll probably look at this in the future, since it'll probably require some shenanigans

2023-07-02 01:01 UTC, Wollywoger commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +	return ..() // todo: add code for checking if arms are disabled through paralysis or damage
i forgot!, either that or i removed/lost the code. I added this in the most recent commit.

2023-07-02 22:47 UTC, MrMelbert commented on maplestation_modules/code/modules/mob/living/carbon/human/ornithid_features/armwings.dm
> +		to_chat(human, span_warning ("You need both of your hands to fly!"))
```suggestion
		to_chat(human, span_warning("You need both of your hands to fly!"))
```

2023-07-02 23:13 UTC, MrMelbert approved these changes

2023-07-02 23:13 UTC, merged