Adds in Beer Eyepatch
MrMelbert/MapleStationCode pull request #277
Opened 2023-05-21 00:24 UTC by Andrymeda

Just an eyepatch that has the same traits as the Beer Sunglasses. There's Hud-Eyepatches, I thought it'd be funny, I also wanted to learn how to add in clothing modularly so this was good practice. (took me like 3 hours.)
Two of them, put in the Bardrobe.

![image](https://github.com/MrMelbert/MapleStationCode/assets/109443978/841ebeef-debf-4d23-890d-03a81a2503e1)
_wait, who is that?_

2023-05-21 00:38 UTC, CRITAWAKETS requested changes
You'll need these changes to past linters.

2023-05-21 00:38 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/clothing/glasses/beer_eyepatch.dm
> +	user.update_worn_glasses()
missing an endline
```suggestion
	user.update_worn_glasses()

```

2023-05-21 00:38 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/vending/wardrobes.dm
> +    added_products = list(
tabs instead of space indents
```suggestion
	added_products = list(
```

2023-05-21 00:38 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/vending/wardrobes.dm
> +        /obj/item/clothing/glasses/eyepatch/reagent = 2
same here with the tabs
```suggestion
		/obj/item/clothing/glasses/eyepatch/reagent = 2
```

2023-05-21 00:38 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/vending/wardrobes.dm
> +        )
more tabs, also end of line
```suggestion
		)

```

2023-06-05 20:13 UTC, MrMelbert commented on maplestation_modules/code/modules/clothing/glasses/beer_eyepatch.dm
> +	clothing_traits = list(TRAIT_BOOZE_SLIDER, TRAIT_REAGENT_SCANNER, FLASH_PROTECTION_FLASH) //flash protection so it's not a direct downgrade with no extra upsides than style
```suggestion
	clothing_traits = list(TRAIT_BOOZE_SLIDER, TRAIT_REAGENT_SCANNER)
	flash_protect = FLASH_PROTECTION_FLASH
```
`FLASH_PROTECTION_FLASH` is not a trait

2023-06-05 20:13 UTC, MrMelbert commented on maplestation_modules/code/modules/clothing/glasses/beer_eyepatch.dm
> +	user.update_worn_glasses()
```suggestion
```
Eyepatch parent covers this

2023-06-05 20:13 UTC, MrMelbert commented on maplestation_modules/code/modules/vending/wardrobes.dm
> +		)
```suggestion
	added_products = list(
		/obj/item/clothing/glasses/eyepatch/reagent = 2,
	)
```

2023-06-05 20:13 UTC, MrMelbert commented on maplestation_modules/code/modules/clothing/glasses/beer_eyepatch.dm
> +	actions_types = list(/datum/action/item_action/flip)
```suggestion
```

2023-06-05 20:42 UTC, merged