Adds a lil overlay to people with temp flavor text
MrMelbert/MapleStationCode pull request #315
Opened 2023-07-24 02:40 UTC by nikothedude

![image](https://github.com/MrMelbert/MapleStationCode/assets/59709059/011002e3-6f58-4ad7-8e29-bffdd0b53f87)

On skyrat, this lil image tripled the usage rate of temp flavor text and made people see it way more

2023-07-24 04:04 UTC, MrMelbert requested changes

2023-07-24 04:04 UTC, MrMelbert commented on maplestation_modules/code/modules/flavor_text/pose_component.dm
> +	living_parent.update_overlays()
- `add_overlay` does not require you pass it a list, so the wrapping is un-necessary
- Calling `update_overlays` also does nothing, it only actually updates overlays if called via `update_appearance`. (`update_appearance(UPDATE_OVERLAYS)`

I think it'd be less liable to break if component just registered `COMSIG_ATOM_UPDATE_OVERLAYS` and added 
the overlay via that

2023-07-24 04:04 UTC, MrMelbert commented on maplestation_modules/code/modules/flavor_text/pose_component.dm
> +	return temporary_flavor_text_indicator
Also this can just be a static var on the pose component itself no reason to make it global

2023-07-24 14:44 UTC, nikothedude commented on maplestation_modules/code/modules/flavor_text/pose_component.dm
> +	living_parent.update_overlays()
ill change it to work like that when i get home

2023-07-25 22:31 UTC, MrMelbert approved these changes

2023-07-25 22:31 UTC, merged