Adds 8 "cantrips" totally not stolen from anywhere to the spellbook
MrMelbert/MapleStationCode pull request #329
Opened 2023-08-18 21:28 UTC by MrMelbert

- Acid Touch
   - A touch spell which applies acid to whatever you touch.
   - Stronger against objects, and even stronger against walls. Costs increases with strength.
      - Can melt a table in one casts, but takes 3-4 to destroy an airlock. 
      - Can melt an iron wall and anything weaker, but not reinforced walls. 

- Mage Hand
   - It gives you telekinesis for X seconds. 
      - Yeah this is kinda lame, I wanted to make it actually do the hand thing but I figure telekinesis is more intuitive. 

- Shock Touch
   - Literally just genetics shock touch but available in magical form. 
   - Has an interaction if you get the actual genetics shock touch. 

- Illusion
   - Summons an illusion of the caster at the target location for a short time.
   - The illusion becomes less obvious the brighter the area is.
 
- Healing Touch
   - A touch spell that heals someone after a do_after. 
   - Also heals pain. 

- Soothe
   - After a short do-after, makes the target a pacifist (mechanical effect) and gives them a alert saying they have been calmed (roleplay effect). 
   - This do-after can be resisted if done to players (by pressing "resist" or attacking). 
   - If cast on AI mobs, such as Pun Pun, it will also stop them from attacking people / being hostile. 

- Finger Flame
   - The Arm Lighter Implant, in magical form. Basically just an on demand lighter with cool flavor.

- Water Control
   - "Wet a dry spot, or dry a wet spot."
   - Target turf and all adjacent either becomes wet, if they're dry, or dry, if they're wet.
   - Making dry costs nothing but mana.
   - Making wet uses water. 
      - There is an innate pool of water you have access to so you can always cast it, but this takes a while to recharge after use. 
      - You can also hold a bucket or beaker of water to draw from it, once expending your innate water.

2023-08-18 22:23 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/client/preferences/spellbook/items/spellbook_item_electrokinesis.dm
> +		without the need for learning any magic or using any mana. It has yet to be determined if humankind has an innate, untapped ability \
shock touch isnt human-only, so "humankind" doesn't really make too much sense

human_oid_kind, maybe?

2023-08-18 22:25 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/client/preferences/spellbook/items/spellbook_item_geomancy.dm
> +		The acid generated is comparable to that of sulfuric acid.\nThis has lead to the spell gaining wide use \
```suggestion
		The acid generated is comparable to that of sulfuric acid.\nThis has led to the spell gaining wide use \
```

2023-08-18 22:34 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/components/touch_component.dm
> +/datum/component/uses_mana/story_spell/touch
I'd recommend adding autodoc here.

2023-08-18 22:44 UTC, CRITAWAKETS commented
Would be interesting if Soothe gained psicodine's sanity-stabilizing ability to make it more than just RP and pacifism.

2023-08-18 23:14 UTC, siliconOpossum commented on maplestation_modules/code/modules/client/preferences/spellbook/items/spellbook_item_healing.dm
> +		due to its ability to provide tranquility those in a state of panic or fear. \n\
```suggestion
		due to its ability to provide tranquility to those in a state of panic or fear. \n\
```

2023-08-19 22:23 UTC, CRITAWAKETS requested changes
This is probably not intentional.

2023-08-19 22:23 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/healing_touch.dm
> +		adjust_pestlevel(weedlevel * 0.5) // increases the amount of weeds, you just healed them!
```suggestion
		adjust_weedlevel(weedlevel * 0.5) // increases the amount of weeds, you just healed them!
```

2023-08-20 23:26 UTC, merged