Old man yaoi 2, but this time purple
MrMelbert/MapleStationCode pull request #350
Opened 2023-09-19 19:22 UTC by Draggeru

Adds the clothing and hair required for Finster, only able to be spawned via game panel

![finstersmol_2](https://github.com/MrMelbert/MapleStationCode/assets/81540056/1208b4e2-6eef-46c0-a0cd-37b8b425ecdb)

2023-09-20 02:02 UTC, CRITAWAKETS commented on maplestation_modules/story_content/noble_equipment/code/nobleclothing.dm
> +	desc = "A luxurious coat made from an unidentifiable material. The jem on the coat begs you to step closer."
```suggestion
	desc = "A luxurious coat made from an unidentifiable material. The gem on the coat begs you to step closer."
```
unless this is actually meant to be Jem and the Holograms in which case strange reference but ok

2023-09-20 02:02 UTC, CRITAWAKETS commented on maplestation_modules/story_content/noble_equipment/code/nobleclothing.dm
> +	desc = "An old pair of boots made from an nidentifable material. These boots have taken their fair share of steps."
```suggestion
	desc = "An old pair of boots made from an unidentifable material. These boots have taken their fair share of steps."
```

2023-09-20 02:03 UTC, CRITAWAKETS requested changes
You forgor to put these in the dme. meaning these won't appear ingame.

2023-09-20 04:49 UTC, Draggeru commented on maplestation_modules/story_content/noble_equipment/code/nobleclothing.dm
> +	desc = "A luxurious coat made from an unidentifiable material. The jem on the coat begs you to step closer."
No I just can't read while sleep deprived

2023-09-20 04:52 UTC, Draggeru commented
> You forgor to put these in the dme. meaning these won't appear ingame.

Unironically works on my machine, so I don't know how to fix this

2023-09-20 08:54 UTC, CRITAWAKETS commented
likely you just forgot to push maplestation.dme or something's been fucky with the git

2023-09-20 16:21 UTC, Draggeru commented
Explain how do,,,

2023-09-21 05:05 UTC, CRITAWAKETS commented
ok so it turns out im dumb and this should werk i somehow didnt notice it wasnt in a new file

2023-09-24 06:03 UTC, doshMobile commented
FINSTER SPOTTED

2023-09-24 17:07 UTC, merged