Cryokinesis: Chapter 2
MrMelbert/MapleStationCode pull request #384
Opened 2023-12-04 00:42 UTC by Andrymeda

# Cryokinesis Chapter 2.

Adding more to the magic I've coded, that being Cryokinesis.

## Current Changes:

### Freeze Person
- You may now Freeze yourself.
- Fixed Freeze Person not stopping Simple Mob AI from working.
- You can now Resist out of the block, which is always half the duration, though it also knocks you down on success.

### Ice Blast
- Previously Ice Knife, now Ice Blast.
- Works basically the same, but removed Wound chance because it's not a knife anymore.

### Ice Knife
- New.
- Summons an Ice Knife that is basically the same as a Survival Knife, except it has a lifetime of 20 seconds. It requires focus to keep it up; every time you hit someone, it's lifetime raises. 

## Future Possible Additions:

- Ability to make a room colder.

2024-02-11 22:18 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +/obj/item/knife/combat/ice/Initialize()
```suggestion
/obj/item/knife/combat/ice/Initialize(mapload)
```
required to make run linters work

2024-02-11 22:45 UTC, CRITAWAKETS requested changes
technically a bug in the original, but should probably be fixed to prevent people from making some utterly insane atmospherics shenanigans

2024-02-11 22:45 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/ice_blast.dm
> +			air.temperature = max(air.temperature + -15, 0)
```suggestion
			air.temperature = max(air.temperature + -15, TCMB)
```
the minimum temperature of atmospherics ingame is meant to be TCMB and not 0, otherwise you get an infinite amount of gas at 0kpa. Even then I'm not sure ice blast should be able to reach absolute zero, probably something more like T0C - 30 (or -30C)

2024-02-12 00:39 UTC, CRITAWAKETS reviewed
Some balance feedback regarding testing in pre-round for the server.

2024-02-12 00:39 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/ice_blast.dm
> +	wound_bonus = 50
Balance Feedback from Testing: This can cause weeping avulsions, probably a little too high.

2024-02-12 00:39 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/magic/story_spells/ice_blast.dm
> +	sharpness = SHARP_EDGED
Balance Feedback from Testing: This is a big ball of ice, likely it should be blunt instead. Also bleed wounds tend to be a lot deadlier than blunt wounds.

2024-06-23 03:22 UTC, MrMelbert requested changes

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_blast.dm
> +		var/datum/gas_mixture/turf_air = nearby_turf?.return_air()
```suggestion
		var/datum/gas_mixture/turf_air = nearby_turf.return_air()
```

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +		qdel(src)
This should use a setup similar to `expire()` in the arm blade...

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	playsound(src, 'sound/effects/glass_step.ogg', 70, TRUE, FALSE)
...So we don't have this `playsound` call in `Destroy` (something we want to avoid)

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	var/mob/living/mymob
This doesn't need to be a datum level var, you can just create it where necessary. Loc is always there to access. 
```suggestion
```

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	mymob = loc
```suggestion
```

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +			span_danger("You hear someone conjuring an ice-blade!")
This deaf message is a little goofy. How would they know they're specifically conjuring an ice blade?
```suggestion
			span_hear("You hear someone conjuring something!")
```
or
```suggestion
			span_hear("You hear magic channeling!")
```

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	playsound(src, 'sound/effects/glass_step.ogg', 70, TRUE, FALSE)
Put this `playsound` in the `expire` function we have.

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	mymob.apply_damage(damage, BRUTE, spell_hand)
You might want to set this to `wound_bonus = CANT_WOUND`, unless you're okay with it occasionally causing you to break an arm or something (this notably tends to happen to people with the frail quirk)

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/icons/obj/weapons/armblade.png
What is this PNG file for?

2024-06-23 03:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
> +	if(do_after(owner, (duration - world.time) / 2, owner))
```suggestion
	if(do_after(owner, (duration - world.time) / 2))
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
> +			span_danger("You hear something being frozen!")
```suggestion
			span_hear("You hear something being frozen!"),
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
> +			span_danger("You hear something being frozen!")
```suggestion
			span_hear("You hear something being frozen!"),
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
> +				span_danger("You hear someone breaking out of an ice cube!")
```suggestion
				span_hear("You hear cracking!")
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
> +		span_danger("The cube around you melts!")
```suggestion
		span_danger("The cube around you melts!"),
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +			span_hear("You hear someone conjuring something!")
```suggestion
			span_hear("You hear someone conjuring something!"),
```

2024-06-23 03:52 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +			span_danger("You hear something shatter!")
```suggestion
			span_hear("You hear something shatter!"),
```

2024-06-23 04:40 UTC, MrMelbert approved these changes

2024-06-23 04:40 UTC, merged