Adds the Isatoa and Ythralian languages
MrMelbert/MapleStationCode pull request #387
Opened 2023-12-15 09:25 UTC by Draggeru

As the title says:

Isatoa is the language that originates from Mu, and is available in the language menu

Ythralian is a language designed for characters like Finster, Randall, and any character that's eldritch or otherwise ancient in nature. Speaking the language around beings that don't know it causes brain damage. This language is available via admins only, due to it causing actual damage to people.

If something breaks it's Melberts fault because he bullied me into learning something.

Icons:

![icons](https://github.com/MrMelbert/MapleStationCode/assets/81540056/d1deaa28-c350-4a9e-8f60-c29ff4a859ae)

2023-12-15 09:28 UTC, Draggeru commented
>Almost all checks fail

This is why I learn nothing new.

2023-12-15 09:44 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/language/isatoan.dm
> +	return
```suggestion
		return
```
needs indentation

2023-12-15 09:47 UTC, CRITAWAKETS requested changes
Currently this doesn't compile so uh, might wanna fix that!

2023-12-15 09:47 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/language/isatoan.dm
> +	return
```suggestion
		return
```

2023-12-15 09:47 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/language/isatoan.dm
> +	listener_real.adjustOrganLoss(ORGAN_SLOT_BRAIN, 10, 100)
```suggestion
	listener.adjustOrganLoss(ORGAN_SLOT_BRAIN, 10, 100)
```
that said im not sure if adjustOrganLoss works on mob/living, might have to cast to mob/living/carbon/human

2023-12-15 09:47 UTC, CRITAWAKETS commented on maplestation_modules/code/modules/language/isatoan.dm
> +/datum/language_holder/skrell
Is this meant to be skrell?

2023-12-15 09:48 UTC, CRITAWAKETS commented
Eldritch/Ythralian should likely be made to have it's brain-damage effect be resisted via a trait rather than understanding the language, since it seems likely that things like divine entities (or people who are Built Different) wouldn't be affected, but would also not understand the language.

2023-12-15 10:41 UTC, Draggeru commented
> Eldritch/Ythralian should likely be made to have it's brain-damage effect be resisted via a trait rather than understanding the language, since it seems likely that things like divine entities (or people who are Built Different) wouldn't be affected, but would also not understand the language.

When you help me code it

2023-12-15 10:41 UTC, Draggeru commented on maplestation_modules/code/modules/language/isatoan.dm
> +/datum/language_holder/skrell
Noh

2023-12-17 23:13 UTC, MrMelbert commented on maplestation_modules/code/modules/language/isatoan.dm
> +	dialect.heard_by_mob_who_lacks_critical_information(src)
```suggestion
	dialect.heard_by_mob_who_lacks_critical_information(src, speaker)
```

2023-12-17 23:13 UTC, MrMelbert commented on maplestation_modules/code/modules/language/isatoan.dm
> +/datum/language/proc/heard_by_mob_who_lacks_critical_information(mob/living/listener)
```suggestion
/datum/language/proc/heard_by_mob_who_lacks_critical_information(mob/living/listener, atom/movable/speaker)
```

2023-12-17 23:13 UTC, MrMelbert commented on maplestation_modules/code/modules/language/isatoan.dm
> +	default_priority = 120
We talked about the curator thing already but this being 120 priority means I think curators will spawn with this language as their default language

2023-12-17 23:13 UTC, MrMelbert commented on maplestation_modules/code/modules/surgery/organs/tongue.dm
> +		/datum/language/isatoa,
Insert this in alphabetical order :)

2023-12-20 05:31 UTC, Draggeru commented on maplestation_modules/code/modules/language/isatoan.dm
> +	default_priority = 120
I forgor D:

2024-01-17 19:59 UTC, MrMelbert approved these changes
I'm gonna come up with a solution for curators / miners getting it myself if you don't, fair warning

2024-01-17 19:59 UTC, merged