[DRAFT] [DOES NOT COMPILE] Park one of the Magic Rework
MrMelbert/MapleStationCode pull request #501
Opened 2024-06-11 01:03 UTC by Wollywoger

## Part one: the rework
basically this is a sweeping refactor of the magic system to both heavily favor signals, and to make magic draw from a mob-contained pool, as opposed to the current global system

This is an old branch originally worked on by Niko, who has disengaged with the server.
theres a huge list of requirements before this can even exit draft stage

## CHECK LIST
**PHASE 0:**
-[ ] figure out what i'm doing (may never get checked)

**PHASE 1: get it up to date**
  Since this is almost a year old, a lot of changes have been made to spells in that time
- [ ] update all melbert spells (and possibly andry's, depending on how things shake out) to work in the new system
- [ ] sub task: Finger Flame
- [ ] sub task: Touch Spells (acid, healing, shock)
- [ ] sub task: projectile spells (Ice knife)
- [ ] sub task: "beam" or hitscan (soothe, illusion, freeze person)
- [ ] subtask: other (water control)
- [ ] perform regression tests to ensure that, atleast at first glance, the spells work as they normally do
- [ ] restore any changed functionality to other spells (i.e those made by ed) that were overwritten

**Phase 2 (wait before continuing): Finishing what was left out**
the refactor was unfinished and sat that way for a good while, so there are some stuff left out. this stuff can be completed out of order, but i prefer finishing the above first.
-[ ] Mana Batteries
-[ ] Mana Crystal Sprites (Ask drag?)
-[ ] Finish Pools

phase three will have essential QoL additions, but **no major gameplay additions, ** beyond what was already planned which will be reserved for phase 2

no screen shots this yet, as its entirely code-based at the moment

2024-06-18 20:19 UTC, Wollywoger commented
i just found out i've been doing everything wrong for the refactor.
lol, guess i gotta start over

2024-09-11 04:33 UTC, Wollywoger commented
forgot to remove "draft" from the title lol

2024-10-01 07:07 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/living_mana.dm
> +	return .
There is a bespoke proc for adding information to the status tab. It is called `get_status_tab_items`. I recommend you utilize that instead of trying to make use of what actions use. It is 100x easier:

```dm
/mob/get_status_tab_items()
    . = ..()
   . += "Mana: [mana_pool.get_mana_amount()]"
```
```dm
/datum/mana_pool/proc/get_mana_amount()
     return "MEDIUM" // put your code here
```

For bonus points, you can accomplish this without even overriding the proc. You can use a signal, `COMSIG_MOB_GET_STATUS_TAB_ITEMS`: 
```dm
/datum/mana_pool/proc/mana_status_report(datum/source, list/status_tab)
     SIGNAL_HANDLER
     status_tab += "MEDIUM" // put your code here
```

2024-10-01 07:08 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/Initialize(mapload, ...)
Remind me to profile this before we merge it. This proc override might be adding a non-zero amount to atom init time.

2024-10-01 07:11 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +	return owner?.get_mana()
This being on `/datum` seems really weird, that action override there also seems weird. Is this still used?

2024-10-01 07:13 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana_chemicals.dm
> +			drinker_pool.adjust_mana(1.5) // regen mana by 1.5 per tick, no attunement
Minor suggestion: I see a fair bit of copypaste from this specific block, maybe add a mob level proc for adjusting personal mana pool, which handles all this for you. (IE, you just do `mob.adjust_personal_mana(1.5)` and it checks for mana pool, soft cap, etc. for you)

2024-10-01 07:15 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +	return (cached_cap ? cached_cap : (transfer_default_softcap ? target_pool.softcap : target_pool.maximum_mana_capacity))
```suggestion
	return cached_cap || (transfer_default_softcap ? target_pool.softcap : target_pool.maximum_mana_capacity)
```
Life hack for slightly more readable code

2024-10-01 07:15 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +		*/
Just leaving one review, but all this commented code should probably be removed before merge

2024-10-01 07:17 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/leylines/leyline_amounts.dm
> +	var/amount = 0
This even need to be a datum anymore? It holds a single number. Could just as easily do
```dm
GLOBAL_LIST_INIT_TYPED(leyline_amounts, /datum/leyline_amount, list(
	"1" = 500,
	"2" = 50,
	"3" = 20,
	"4" = 1,
))
```
(Just make sure you text2num)

2024-10-01 07:17 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/leylines/leylines.dm
> +	var/datum/leyline_amount/leyline_amount = pick_weight(GLOB.leyline_amounts)
Speaking of which, probably no need for `GLOB.leyline_amounts` to be a global list, it seems like it can just be a static list in this proc

2024-10-01 07:19 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		var/mana_to_send = tgui_input_number(user, "How much mana do you want to send to the battery? Max Capacity: [mana_pool.maximum_mana_capacity]", "Send Mana", max_value = mana_pool.maximum_mana_capac
You need to sanity check that the person is still holding the battery, and is in a valid state to transfer, after this input resolves

This is called an input stall, and it's a very common exploit

Preventing it often looks like this:

```dm
var/i = input(user, "Do something?", "Yes", "No)
if( QDELETED(user) || user.incapacitated() )
    return
```

2024-10-01 07:20 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		var/mana_to_draw = tgui_input_number(user, "How much mana do you want to draw from the battery? Soft Cap (You will lose mana when above this!): [user.mana_pool.softcap]", "Draw Mana", max_value = m
Same here. 

If you don't have sanity it means someone can open the window, drop it, walk to the opposite side of the map, and can still withdraw whatever mana

2024-10-01 07:20 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "canceled draw.")
```suggestion
		balloon_alert(user, "canceled draw")
```

2024-10-01 07:20 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
```suggestion
		balloon_alert(user, "no mana pool!")
```

2024-10-01 07:20 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
```suggestion
		balloon_alert(user, "no mana pool!")
```

2024-10-01 07:20 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "canceled send.")
```suggestion
		balloon_alert(user, "canceled send")
```

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	mana_pool = /datum/mana_pool/mana_star
Isn't `mana_pool` an instanced datum? why setting it to typepath, for all of these?

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	return mana_pool
And like isn't this supposed to return a typepath? Don't you want this to be `return /datum/mana_pool/mana_star`?

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "canceled draw.")
```suggestion
		balloon_alert(user, "canceled draw")
```

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
```suggestion
		balloon_alert(user, "no mana pool!")
```

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "drawing mana....")
Input thing here too

2024-10-01 07:22 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	ADD_TRAIT(src, TRAIT_POOL_AVAILABLE_FOR_CAST, REF(src))
```suggestion
	ADD_TRAIT(src, TRAIT_POOL_AVAILABLE_FOR_CAST, INNATE_TRAIT)
```

2024-10-01 07:23 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/flare.dm
> +
Empty block?

2024-10-01 07:25 UTC, MrMelbert commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define BASE_MANA_OVERLOAD_THRESHOLD BASE_MANA_CAPACITY * 0.9
```suggestion
#define BASE_MANA_OVERLOAD_THRESHOLD (BASE_MANA_CAPACITY * 0.9)
```

2024-10-01 07:25 UTC, MrMelbert commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define NO_CATALYST_COST_MULT 2 // DEBUG! BASE VALUE SHOULD BE 4!
?

2024-10-02 03:29 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +	return owner?.get_mana()
this was testing/sanity, the datum base shouldn't be necessary anymore

2024-10-02 03:30 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define NO_CATALYST_COST_MULT 2 // DEBUG! BASE VALUE SHOULD BE 4!
OH RIGHT
i did this because for some reason the no-catalyst-mult wasn't applying properly at the time, i should just remove the comment cause an x4 multiplier is also too high

2024-10-02 03:34 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana_chemicals.dm
> +			drinker_pool.adjust_mana(1.5) // regen mana by 1.5 per tick, no attunement
actually, good idea, i'll probably have a "safe_adjust_personal_mana" and a "adjust_personal_mana" for if you want to keep it below softcap, and one if you want to go over

2024-10-02 03:48 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/flare.dm
> +
removing in the next commit, will resolve when committed

2024-10-02 04:08 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define BASE_MANA_OVERLOAD_THRESHOLD BASE_MANA_CAPACITY * 0.9
applied in batch #1

2024-10-02 04:09 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/flare.dm
> +
applied in first batch

2024-10-02 04:09 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define NO_CATALYST_COST_MULT 2 // DEBUG! BASE VALUE SHOULD BE 4!
relevant code removed in first batch

2024-10-02 04:10 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	ADD_TRAIT(src, TRAIT_POOL_AVAILABLE_FOR_CAST, REF(src))
applied in first batch

2024-10-02 04:10 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +	return (cached_cap ? cached_cap : (transfer_default_softcap ? target_pool.softcap : target_pool.maximum_mana_capacity))
applied in first batch

2024-10-02 04:35 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +	return owner?.get_mana()
removed with batch 1 and a bit of removal

2024-10-02 18:53 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
added in batch 3

2024-10-02 18:53 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
added in batch 3

2024-10-02 18:53 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "canceled draw.")
added in batch 3

2024-10-02 18:53 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "you have no mana pool!")
added in batch 3

2024-10-02 19:00 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	mana_pool = /datum/mana_pool/mana_star
replaced it with the get_initial_mana_pool set up in batch 4

2024-10-02 19:00 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +	return mana_pool
applied it in batch 4

2024-10-04 17:08 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		var/mana_to_draw = tgui_input_number(user, "How much mana do you want to draw from the battery? Soft Cap (You will lose mana when above this!): [user.mana_pool.softcap]", "Draw Mana", max_value = m
should be fixed, let me know if these still remain.

2024-10-04 17:08 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		var/mana_to_send = tgui_input_number(user, "How much mana do you want to send to the battery? Max Capacity: [mana_pool.maximum_mana_capacity]", "Send Mana", max_value = mana_pool.maximum_mana_capac
should be fixed, let me know if these still remain.

2024-10-04 17:08 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/mana_batteries.dm
> +		balloon_alert(user, "drawing mana....")
should be fixed, let me know if these still remain.

2024-10-04 17:39 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana_chemicals.dm
> +			drinker_pool.adjust_mana(1.5) // regen mana by 1.5 per tick, no attunement
implemented

2024-10-04 18:18 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/living_mana.dm
> +	return .
did it using the comsig.

2024-10-05 01:34 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/leylines/leyline_amounts.dm
> +	var/amount = 0
turned into a static list on the initial_leyline_amount proc, which uses text2num as requested

2024-10-05 01:34 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/sources/leylines/leylines.dm
> +	var/datum/leyline_amount/leyline_amount = pick_weight(GLOB.leyline_amounts)
added as requested

2024-10-05 02:14 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +		*/
should have scoured out all instances of this by now, resolving assuming i didn't miss any

2024-11-01 17:32 UTC, Wollywoger commented
ran prelim tests:

Without the PR
on runtimestation init completes in ~19 seconds 
Initialized Atoms subsystem within 4.83 seconds!
metastation init completes in ~26 seconds
 Initialized Atoms subsystem within 12.64 seconds! 

With the PR
runtime station: 
init completes in ~16 seconds somehow
Initialized Atoms subsystem within 5.59 seconds!
metastation
complete init in ~27-28 seconds
 Initialized Atoms subsystem within 14.98 seconds! 

EST gain of 14%-16% seconds on atom init
these are non-conclusive tests as i've only done 2 tests, and still need to rule out deviation fully

2024-11-15 00:35 UTC, MrMelbert requested changes
Final review for good

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/__DEFINES/magic/magic_bitflags.dm
> +#define ATOM_HAS_INITIAL_MANA_POOL ()
Unused

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define SPECIES_BASE_MANA_CAPACITY_MULT 1
Unused

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/__DEFINES/magic/mana_charge_bitflags.dm
> +#define MANA_RECHARGE_SOURCE_ETHEREAL (1<<0)
Unused

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/datums/components/crafting/recipes.dm
> +				)
```suggestion
	reqs = list(
		/obj/item/mana_battery/mana_crystal/cut = 1,
		/obj/item/stack/sheet/mineral/gold = 1, // cheap for now
	)
```

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/Destroy(force, ...)
After consideration I think we should demodularize this as well

Additionally I think this mana pool cleanup thing could be more ergonimic, like you should just be able to qdel the mana pool and it will automatically call `set_mana_pool(null)` for you (handled via `/mana_pool/Destroy`)

(This `set_mana_pool` here is quite expensive even though it does absolutely nothing normally)

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/initialize_mana_pool()
Auto doc would be appreciated

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/get_initial_mana_pool_type()
Same

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/set_mana_pool(datum/mana_pool/new_pool)
Same, (it already has one but it doesn't say much)

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/get_mana_pool_lazy()
Same, though this proc looks unused

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/initialize_mana_pool_if_possible()
Same, though it also looks unused ultimately

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/can_have_mana_pool(datum/mana_pool/new_pool)
Same

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +		return MANA_POOL_FULL*/
Commented code?

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/mana/sources/leylines/leylines.dm
> +	"4" = 10
```suggestion
		"1" = 5000,
		"2" = 500,
		"3" = 200,
		"4" = 10
```

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/components/touch_component.dm
> +	)
```suggestion
	list/datum/attunement/attunements,
)
```

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/components/touch_component.dm
> +/datum/component/uses_mana/touch_spell/proc/can_touch(
This proc does not do anything anymore, it just returns, is that intended

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/components/touch_component.dm
> +//	RegisterSignal(parent, COMSIG_SPELL_TOUCH_HAND_HIT, PROC_REF(handle_touch))
Some commented out signals too, can probably delete?

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/finger_flame.dm
> +		return NONE */
Commented code

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	return ..() * ice_knife_spell.ice_knife_cost */ // this is being held on to now, will be killed before PR time
Is it time to kill it or what

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +		/// What the mana cost is, affected by Armblade variant.
```suggestion
	/// What the mana cost is, affected by Armblade variant.
```

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/illusion.dm
> +	.[/datum/attunement/light] = illusion_attunement */
More commented

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/mana_charge.dm
> +	do_after(cast_on, 7 SECONDS) // don't want this mid combat.
This do after is doing nothing

You have to `return` if it returns false (doafter fails)

Also for spells, you would put doafters in `before_cast` and not in `cast`

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/mana_charge.dm
> +	do_after(cast_on, 20 SECONDS) // don't want this mid combat.
Same

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/shock_touch.dm
> +		)
```suggestion
	)
```

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/shock_touch.dm
> +// 	var/datum/component/uses_mana/story_spell/touch/shock_touch/touch = magic_shock.GetComponent(/datum/component/uses_mana/story_spell/touch/shock_touch)
deletable comment?

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/shock_touch.dm
> +//	var/datum/component/uses_mana/story_spell/touch/shock_touch/touch = magic_shock.GetComponent(/datum/component/uses_mana/story_spell/touch/shock_touch)
deletable comment?

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/story_spells/water_control.dm
> +	return ..() * spell.wetness_pool.total_volume * wet_cost_per_unit */
More comments

2024-11-15 00:35 UTC, MrMelbert commented on maplestation_modules/code/modules/magic/todo.txt
Prolly can delete this

2024-11-15 00:45 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/Initialize(mapload, ...)
this was performed successfully, resolving this comment and removing the task

2024-11-15 01:36 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/components/touch_component.dm
> +/datum/component/uses_mana/touch_spell/proc/can_touch(
i'll have to run tests on the significance- i'm not entirely sure the necessity of it in the first place

2024-11-15 01:41 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/magic_bitflags.dm
> +#define ATOM_HAS_INITIAL_MANA_POOL ()
deleted

2024-11-15 01:41 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/magic_defines.dm
> +#define SPECIES_BASE_MANA_CAPACITY_MULT 1
deleted

2024-11-15 01:41 UTC, Wollywoger commented on maplestation_modules/code/__DEFINES/magic/mana_charge_bitflags.dm
> +#define MANA_RECHARGE_SOURCE_ETHEREAL (1<<0)
deleted

2024-11-15 01:41 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana_pool.dm
> +		return MANA_POOL_FULL*/
deleted

2024-11-15 01:41 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/finger_flame.dm
> +		return NONE */
deleted - might have to do something if this is significant, however

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/ice_knife.dm
> +	return ..() * ice_knife_spell.ice_knife_cost */ // this is being held on to now, will be killed before PR time
deleted

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/illusion.dm
> +	.[/datum/attunement/light] = illusion_attunement */
deleted

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/shock_touch.dm
> +// 	var/datum/component/uses_mana/story_spell/touch/shock_touch/touch = magic_shock.GetComponent(/datum/component/uses_mana/story_spell/touch/shock_touch)
deleted

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/shock_touch.dm
> +//	var/datum/component/uses_mana/story_spell/touch/shock_touch/touch = magic_shock.GetComponent(/datum/component/uses_mana/story_spell/touch/shock_touch)
deleted

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/story_spells/water_control.dm
> +	return ..() * spell.wetness_pool.total_volume * wet_cost_per_unit */
deleted

2024-11-15 01:42 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/todo.txt
deleted

2024-11-15 05:22 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/set_mana_pool(datum/mana_pool/new_pool)
done, kept in unless they're deemed completely redundant

2024-11-15 05:22 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/get_mana_pool_lazy()
done, kept in unless it's deemed completely redundant

2024-11-15 05:22 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/can_have_mana_pool(datum/mana_pool/new_pool)
done

2024-11-15 05:22 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/initialize_mana_pool_if_possible()
done, kept in unless it's deemed completely redundant

2024-11-15 05:22 UTC, Wollywoger commented on maplestation_modules/code/modules/magic/mana/mana.dm
> +/atom/movable/proc/get_initial_mana_pool_type()
done

2024-12-02 03:04 UTC, MrMelbert approved these changes

2024-12-02 03:04 UTC, merged