Polite Split Personality (non-random Split Personality Variant)
MrMelbert/MapleStationCode pull request #543
Opened 2024-07-30 19:12 UTC by Andrymeda

This version of Split Personality, instead of randomly changing, adds a new action shared between the two players which can be turned on or off.

If both of them are on, the players switch control on mutual demand instead.

Don't ask me why.

2024-08-03 02:07 UTC, MrMelbert commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	var/non_controller
What is this `var/non_controller` doing here?

2024-08-03 02:07 UTC, MrMelbert commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	. = ..()
```suggestion
	. = ..()
	if(!.)
		return
```

2024-08-03 02:07 UTC, MrMelbert commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	var/mob/living/split_personality/non_controller
For all of these, you need to set `[blar] = null` in `/datum/action/request_switch/Destroy`

2024-08-03 02:07 UTC, MrMelbert commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	trauma = target
Why is this in `Trigger`?

Actually you don't need this at all, if you need to cast trauma you can just do it in whatever proc it's necessary:
`var/datum/brain_trauma/severe/split_personality/trauma = target`

2024-08-03 02:19 UTC, MrMelbert commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	var/mob/living/split_personality/non_controller
Actually, I don't think you need any of these on the datum

You should be able to put them in the proc it's used?

2024-08-04 21:12 UTC, SmArtKar commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	else if(trauma.current_controller == /*STRANGER*/1)
Should probably be #define PERSONALITY_SWITCH_OWNER 0 and #define PERSONALITY_SWITCH_STRANGER 1 instead of comments

2024-08-04 21:13 UTC, SmArtKar requested changes

2024-08-04 21:13 UTC, SmArtKar commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	non_controller.balloon_alert(controller, "your brain tickles")
This should probably be 
```
controller.balloon_alert(controller, "your brain tickles")
controller.balloon_alert(non_controller, "your brain tickles")
```

2024-08-04 21:13 UTC, SmArtKar commented on maplestation_modules/code/datums/brain_damage/split_personality.dm
> +	non_controller.balloon_alert(controller, "your brain tickles")
same here

2024-11-05 20:00 UTC, merged