Adds Umbrellas
MrMelbert/MapleStationCode pull request #575
Opened 2024-08-30 14:10 UTC by Constellado

# What's this?
Adds umbrellas to the game!
They can open and close and they look real neat!
## Why?
Because we need handheld parasols or umbrellas for the beach!
TO DO:
- [x] Inhand sprites for Volkan's umbrella
- [x] Item sprite for a basic umbrella
- [x] Inhand sprites for a basic umbrella
- [x] item sprite for a parasol
- [x] inhand sprites for a parasol
- [x] Make a Volkan's umbrella and parasol in code.
- [x] Make Volkan's umbrella stop radiation when open. It has radiation shielding.
- [x] Have the plain umbrellas have colour options!
- [x] Add umbrellas to the preferences menu.

## Sprites so far:
### Basic umbrella
![image](https://github.com/user-attachments/assets/e8209917-504d-4348-ab8b-1482d03be03d)![image](https://github.com/user-attachments/assets/cc889986-87f4-4f64-8eb3-08463896cc28)
inhand open:
![image](https://github.com/user-attachments/assets/b4fafdde-146f-4850-bdbf-9884357ab5cd)![image](https://github.com/user-attachments/assets/effec589-2576-46c2-a21a-700171d16f3d)![image](https://github.com/user-attachments/assets/2985882f-6a41-4571-bdaf-79c472816576)![image](https://github.com/user-attachments/assets/c03df8fa-4c9a-4d52-99f8-c04fac7d3cf8)
inhand closed:
![image](https://github.com/user-attachments/assets/0d353824-c289-4848-81f1-c725d348796d)![image](https://github.com/user-attachments/assets/19dd7f66-40dd-4516-ae65-8b16de4d244a)![image](https://github.com/user-attachments/assets/d3314804-5fda-427b-8a03-3f05bd9c97e6)![image](https://github.com/user-attachments/assets/537c038a-cc2e-4b32-97b7-669878e59dcf)

### Black Parasol
![image](https://github.com/user-attachments/assets/454fcd25-a7bf-4a7c-b205-e0ef654b52a0)![image](https://github.com/user-attachments/assets/312f8ef8-a227-4ab8-a2af-87836aeb912c)

Inhand open:
![image](https://github.com/user-attachments/assets/c50e8e26-a33b-4b7e-be16-5bbd95b905c5)![image](https://github.com/user-attachments/assets/88733ac1-c642-4364-a163-b7646bf8fcc9)![image](https://github.com/user-attachments/assets/5a0da961-6499-4f11-9cc9-444b7eafd8f1)![image](https://github.com/user-attachments/assets/331ee1d4-800f-441e-b7d4-7bf584a136bb)

inhand closed:
![image](https://github.com/user-attachments/assets/bf39f2d4-2023-4710-bed5-41a36a74ce05)![image](https://github.com/user-attachments/assets/7d864bf5-e2a3-4bea-9d71-2d15336f3ca0)![image](https://github.com/user-attachments/assets/cffad3bc-ed99-44ca-90b7-5644b0872568)![image](https://github.com/user-attachments/assets/1e48b1db-7206-4e3c-b3ce-66c438bca0d2)

### Volkan's umbrella
![image](https://github.com/user-attachments/assets/f7d4b233-8168-4dc9-a72f-d5d0cc5df334)![image](https://github.com/user-attachments/assets/848719f2-9d53-414f-8b6e-5b3a9e839aaf)
Inhand open:
![image](https://github.com/user-attachments/assets/adc19cbf-4861-42e3-8d95-6f22244ba5ea)![image](https://github.com/user-attachments/assets/1ced11ce-3123-4c2d-97e4-9d5f42b5be86)![image](https://github.com/user-attachments/assets/e5ca034d-3bea-4046-b1c8-5e369ff3384e)![image](https://github.com/user-attachments/assets/40588805-9da5-4150-bfbc-9191ab195763)

Inhand closed:
![image](https://github.com/user-attachments/assets/4232dea9-794d-457c-84c9-bbd59482e1ef)![image](https://github.com/user-attachments/assets/221e9c84-4876-49f1-9c0e-dbddf64b96f8)![image](https://github.com/user-attachments/assets/503e9f38-008f-4ae1-aabc-1940d7c62991)![image](https://github.com/user-attachments/assets/42a895c0-27b3-4089-85ac-9ccb2790a5eb)

2024-08-31 22:33 UTC, MrMelbert commented on maplestation_modules/code/game/objects/items/umbrellas.dm
> +	owner.update_appearance()
You should be able to just do 
```suggestion
	owner.update_held_items()
```
and it'd handle everything for you?

2024-08-31 22:33 UTC, Draggeru commented
Based Drag core PR

2024-08-31 22:33 UTC, MrMelbert commented on maplestation_modules/code/game/objects/items/umbrellas.dm
> +/obj/item/umbrella/
```suggestion
/obj/item/umbrella
```

2024-09-01 23:06 UTC, MrMelbert requested changes

2024-09-01 23:06 UTC, MrMelbert commented on maplestation_modules/story_content/volkan_equipment/code/volkanitems.dm
> +		REMOVE_TRAIT(user, TRAIT_RADIMMUNE, INNATE_TRAIT)
The way you currently have it, this trait will be permanent if you open up an umbrella and then just drop it. 

Also `INNATE_TRAIT` is an inappropriate trait source

You'd need to add a system so that it adds the trait in `pickup` if it's active, removes the trait in `dropped` regardless if it's active or not, and then in `on_transform` you'd have this code still*.

2024-09-01 23:06 UTC, MrMelbert commented on maplestation_modules/story_content/volkan_equipment/code/volkanitems.dm
> +		REMOVE_TRAIT(user, TRAIT_RADIMMUNE, INNATE_TRAIT)
*Except I think 1. `user` is not nullsafe in this code, and 2. this would give people using telekinesis to open the umbrella rad immunity

2024-11-05 19:59 UTC, merged